### ISSUE TITLE
What spec did you use for the SMPTE 2022-1 FEC implementation ?

### ISSUE THREAD

**Issue by boxerab** [davidfischer-ch/pytoolbox#33]
Hi David,

Would you mind letting me know what documents you used for your FEC implementation ?
We are looking into doing this on GStreamer, and hoping to find a freely available
standard to work from.

https://bugzilla.gnome.org/show_bug.cgi?id=789074

Thanks so much,
Aaron

**Comment by davidfischer-ch** [comment]
Hi Aaron,

Of course!

Please check https://github.com/davidfischer-ch/smpte2022lib/tree/master/Norms.
I don't remember which one exactly but the one that define 1D/2D FEC with basic XOR operation.

Best Regards,

David

**Comment by davidfischer-ch** [comment]
https://github.com/davidfischer-ch/pytoolbox/blob/master/pytoolbox/network/smpte2022/base.py#L20

RTFM (kidding)

**Comment by boxerab** [comment]
Thank you ,sir!
